export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS"
export const CREATE_CLASS_ERROR = "CREATE_CLASS_ERROR"
export const FETCH_CLASS = "FETCH_CLASS"
export const FETCH_CLASS_ERROR = " FETCH_CLASS_ERROR"
export const BEFORE_STATE_CLASS = "BEFORE_STATE_CLASS"
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS"
export const GET_CLASS_ERROR = "GET_CLASS_ERROR"
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS"
export const DELETE_CLASS_ERROR = "DELETE_CLASS_ERROR"



