

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const FETCH_USER = "FETCH_USER"
export const FETCH_USER_ERROR = "FETCH_USER_ERROR"
export const BEFORE_STATE = "BEFORE_STATE"







